before_script:
  - npm install --quiet
  - npm run build

stages:
  - test
  - deploy

test:
  stage: test
  tags:
    - test
  script:
    - npm test

deploy:
  stage: deploy
  tags:
    - deploy
  script:
    - echo 'NOOP'

  only:
    - master
